pluginManagement { repositories { maven { url = 'https://maven.fabricmc.net/' }; mavenCentral(); gradlePluginPortal() } }
rootProject.name = 'vanilla-plusplus-quality-of-life-suite'
include 'combined-compat', 'chalk-compat', 'shared-region-maps', 'toolpouch-atlas-elytra'
project(':combined-compat').projectDir = file('components/combined-compat')
project(':chalk-compat').projectDir = file('components/chalk-compat')
project(':shared-region-maps').projectDir = file('components/shared-region-maps/working')
project(':toolpouch-atlas-elytra').projectDir = file('components/toolpouch-atlas-elytra/working')
