org.gradle.jvmargs=-Xmx2G -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true

mod_version=1.0.1+26.3
maven_group=com.thenathe
archives_base_name=amethyst-curse-cleanser

mod_id=amethyst_curse_cleanser
mod_name=Amethyst Curse Cleanser
mod_description=Remove Binding and Vanishing curses with amethyst, receiving an echo shard in return.
