plugins { id 'net.fabricmc.fabric-loom' version '1.17.20' }
version = '1.0.5-suite.1+26.3'
group = 'com.thenathe'
base { archivesName = 'toolpouch-atlas-elytra-compat' }
dependencies {
 minecraft 'com.mojang:minecraft:26.3'
 implementation 'net.fabricmc:fabric-loader:0.19.5'
 implementation 'net.fabricmc.fabric-api:fabric-api:0.161.0+26.3'
 compileOnly rootProject.fileTree('libs') { include '*.jar', 'compile-only/*.jar' }
}
processResources { inputs.property 'version', project.version; filesMatching('fabric.mod.json') { expand(version: project.version) } }
tasks.withType(JavaCompile).configureEach { options.encoding = 'UTF-8'; options.release = 25 }
java { withSourcesJar(); sourceCompatibility = JavaVersion.VERSION_25; targetCompatibility = JavaVersion.VERSION_25 }
jar { from('LICENSE') }

if (project.hasProperty("compilerVersion")) tasks.withType(JavaCompile).configureEach { javaCompiler = javaToolchains.compilerFor { languageVersion = JavaLanguageVersion.of(project.property("compilerVersion").toString().toInteger()) } }

if (project.hasProperty("javac")) tasks.withType(JavaCompile).configureEach { options.fork = true; options.forkOptions.executable = project.property("javac") }
